apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ubuntu16
spec:
  selector:
    matchLabels:
      app: ubuntu16
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu16
    spec:
      containers:
      - name: ubuntu16
        image: localregistry.local:5000/ubunciak
        imagePullPolicy: IfNotPresent
        command: ["sleep"]
        args: ["10000"]
        ports:
        - containerPort: 22
---

apiVersion: v1
kind: Service
metadata:
  name: ubuntu16
spec:
  type: NodePort
  selector:
    app: ubuntu16
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22